version: "3"
services:
  node-app:
     build: .
     container_name: "node-service-web"
     ports:
        - 8000:8000
     restart: always
  mongo:
    image: mongo
    container_name: mongo-service
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

